services:
  # A Docker web service
  - type: web
    name: mental-health-api-v1
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ./scripts/api/app:app --host 0.0.0.0 --port $PORT