# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  pull_request:
    branches: [ master ]

#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'mental-health-fastapi' }}

# Your workflows jobs.
jobs:
  deploy:
    name: Build, Push and Release FastAPI Docker container to Heroku
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v3
        
      # Build Docker image
      - name: Docker Heroku build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      
      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
